### PR TITLE
Upgrade to PF4v4

### PR DESCRIPTION
**Pull request by PanSpagetka**
Update to new version of PF.
Screenshot from 2020-06-18 10-56-13
Screenshot from 2020-06-18 10-56-26
Screenshot from 2020-06-18 10-57-09
Screenshot from 2020-06-18 10-57-27

### CODE REVIEW

**Comment by katierik** [comment]
Looking at this, a couple things I noticed:
Xnip2020-06-18_08-32-38
There is a blue bottom border on this text field - is that there all the time or is it in focus in this screenshot?


Xnip2020-06-18_08-35-01
What H level is the pointed out item? PF changed text sizes and it looks a bit different than my expectation.

Xnip2020-06-18_08-37-01
The spacing in the card on this one looks like it is larger than the others. It should have the same overall padding as the other cards (16px I believe)

Looking good!

**Comment by PanSpagetka** [comment]
@katierik `headingLevel` for Platform summary is `h4` and the size is `xl`

**Comment by PanSpagetka** [comment]
test failure is PF related. I ahve opened an issue: https://github.com/patternfly/patternfly-react/issues/4415

**Comment by aleccohan** [comment]
@PanSpagetka has the paternfly-react issue above been resolved?

**Comment by PanSpagetka** [comment]
@aleccohan Yep, it should be fixed now

**Comment by Jason-RH** [comment]
:+1: Gonna go ahead and merge to start working with the new changes

**Pull request merged**
