### PR TITLE
Console link fix

### PR DESCRIPTION
**Pull request by arivepr**
Aims to close [this card](https://issues.redhat.com/browse/RHCLOUD-14909)

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
@arivepr I see a bunch of commits that I would not expect. Any changes you have also included changes from https://github.com/RedHatInsights/insights-remediations-frontend/pull/252 in this PR?

**Review by karelhala — APPROVED** [review]

**Comment by karelhala** [comment]
@Hyperkid123 looks like it. @arivepr can you interactively rebase and remove those commits that are not part of this PR?

**Comment by arivepr** [comment]
> @Hyperkid123 looks like it. @arivepr can you interactively rebase and remove those commits that are not part of this PR?

am doing now, could I get some eyes on the [#252](https://github.com/RedHatInsights/insights-remediations-frontend/pull/252) if you guys get a chance?

**Comment by arivepr** [comment]
should be good to go now, only contains the link change

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
