### PR TITLE
Use new Remediation landing page design

### PR DESCRIPTION
**Pull request by PanSpagetka**
Screenshot from 2020-05-05 16-43-49

Screenshot from 2020-05-07 13-48-04
Screenshot from 2020-05-07 13-47-51

Screenshot from 2020-05-05 16-44-54

https://marvelapp.com/j3b9b7e/screen/67698074
https://projects.engineering.redhat.com/browse/RHCLOUD-5542
https://projects.engineering.redhat.com/browse/RHCLOUD-4319
https://projects.engineering.redhat.com/browse/RHCLOUD-5454

### CODE REVIEW

**Comment by mmenestr** [comment]
Hey Robin, could you add some screenshots here of your updates?

**Comment by PanSpagetka** [comment]
Oh, yeah, of course!

**Comment by katierik** [comment]
I'm not seeing all the changes in the screenshot you have above? 
https://marvelapp.com/j3b9b7e/screen/67698074

By item:
1 - Bulk select: Not seeing it
2 - Playbook capitalization: fixed in the button but not in the search bar
3 - Button style in toolbar: Not seeing it
4 - Delete font color: Not in screenshot
5 - Pagination should be compact: Not seeing it
6 - No action
7 - Bulk actions are available individually: Not seeing it

**Comment by PanSpagetka** [comment]
I was checked out to wrong branch, when making the screenshot...I will update in one minute.

**Comment by katierik** [comment]
Seeing all the changes now! 👍

**Comment by mmenestr** [comment]
Robin - just for this issue about the bulk select https://projects.engineering.redhat.com/browse/RHCLOUD-4319
I notice that when there is a selection in your screenshots, the box is grey, but in PF, when something is selected, the box is blue! Wondering if you're using the correct component or if there is something else going on: https://www.patternfly.org/v4/documentation/react/demos/bulkselecttable#simple Either way, the box should be blue when selected!

**Comment by PanSpagetka** [comment]
I think that is a browser thing. I have grey checkboxes even at PF site.

**Comment by mmenestr** [comment]
Oh, i forgot that happens - looks good to me then! Thanks, Robin!!

**Comment by mmenestr** [comment]
Oh wait actually, small thing - if there's only 1 thing selected out of many possibilities, it should be a "partial" check in the box. Like this! so instead of a checkmark in the top bulk select, it should be a "-"
image

**Comment by PanSpagetka** [comment]
@mmenestr I have added 3 state checkbox and new sreenshots ;)

**Comment by mmenestr** [comment]
hahahah amazing, thank you! LGTM :)

**Pull request merged**
