### PR TITLE
[REMEDY-142] Convert alerts to notifications

### PR DESCRIPTION
**Pull request by johnsonm325**
The original issue was that when deleting a remediation playbook, the page would redirect and remove the alert almost immediately. This is because the alert was being rendered inside of the component that was being directed away from. This led me to remove the alert and implement dispatching notifications.

To reproduce:

- open details of a Remediation
- select Delete remediation from the kebab
- delete the remediation

The correct alert is displayed, and the page is redirected, but the alert then immediately disappears.

Besure to test all of the locations where I've changed to `dispatchNotifications`.

# Description

Associated Jira ticket: # (issue)

Please include a summary of the change, what this fixes/creates/improves.

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Review by adonispuente — CHANGES_REQUESTED** [review]
The number of systems is always incorrect when deleting a system in a remediations details. 


https://user-images.githubusercontent.com/60629070/212412803-b350d6d6-94a1-4cb9-b874-5611a2ba7c0f.mp4

**Comment by adonispuente** [comment]
I want to be sure im checking all the right places. 
When deleting remediations on the mail page /remediations, there is no alert. Is this intended?
Alerts are to be shown when
- Archiving a remediation
- removing an action
- removing a system (via remove system button and with the elipse)
- renaming a remediation
- downloading a playbook
- executing a playbook
am I missing any?

**Comment by johnsonm325** [comment]
> The number of systems is always incorrect when deleting a system in a remediations details.
> 
>  video1904724360.mp4

This is a different bug. We should create a new card for this and fix is separately.

**Comment by johnsonm325** [comment]
> I want to be sure im checking all the right places. When deleting remediations on the mail page /remediations, there is no alert. Is this intended? Alerts are to be shown when
> 
> * Archiving a remediation
> * removing an action
> * removing a system (via remove system button and with the elipse)
> * renaming a remediation
> * downloading a playbook
> * executing a playbook
>   am I missing any?

I checked on console.stage.redhat.com and it seems that deleting a playbook from the main page does not create a notification.

**Comment by adonispuente** [comment]
@johnsonm325 Did I get all the places im supposed to look for notifications? 
I should have clarified, theres a notification for deleting a playbook inside the playbooks details

**Comment by johnsonm325** [comment]
> @johnsonm325 Did I get all the places im supposed to look for notifications? I should have clarified, theres a notification for deleting a playbook inside the playbooks details

Yeah, this seems right

**Review by adonispuente — APPROVED** [review]
LGTM!

**Pull request merged**
