### PR TITLE
Features/total issues resolved

### PR DESCRIPTION
**Pull request by Jason-RH**
Mocks: https://marvelapp.com/prototype/e6f0j0e/screen/69020399
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-7467

Getting this PR up to get some eyes on it. A lot of refactoring. Converted Home.js to a functional component to make attaching the toolbar to the header a bit easier.

WIP/Todo items:
- remediations.resolved_count is currently a placeholder till it's ready on the backend
- Animated progress bar - follow up task/PR

Screenshots:

(Landing Page)
total_issues_landing

(Card Menu)
total_issues_kebab

(Archived)
total_issues_archived

(Toolbar Menu)
total_issues_toolbar_kebab

(Filtered)
total_issues_filtered

### CODE REVIEW

**Comment by katierik** [comment]
Looking at the text sizes, I think an adjustment would work well: 
image

**Comment by katierik** [comment]
For the filtered state, we need to add filter chips. I'll add to mock, but you should be able to reference pretty much any table on c.rh.c :)

**Comment by Jason-RH** [comment]
(filter with chip)
total_issues_filter_chip

**Comment by Jason-RH** [comment]
@katierik A few UX questions for you:
- Should the toolbar kebab menu have an option to bulk archive/restore?
- Should card kebab menu have an option to delete? 
- Should the toolbar include a page selector? This is usually at the bottom of the page so wasn't sure how to handle it here if at all
- Should there be a different 'empty' state shown when all playbooks are archived but not deleted? It could include a toggle to show archived playbooks or something.

**Pull request merged**
